In [8]:
import numpy as np

#### Parte 1: Creación y manipulación de arrays

##### Crear un array: Crea un array de 10 elementos enteros aleatorios entre 1 y 100. Imprime el array generado

In [4]:
# Crear array de 10 elementos aleatorios entre 1 y 100
array = np.random.randint(1, 101, size=10)
# Imprimir el array
print("Array generado:", array)

Array generado: [71 21 24 32 93 67 55 92 38 66]


##### Reshape: A partir del array anterior, convierte este array en una matriz de 2x5.

In [5]:
# Reshape a matriz 2x5
matriz = array.reshape(2, 5)
print("\nMatriz 2x5:")
print(matriz)


Matriz 2x5:
[[71 21 24 32 93]
 [67 55 92 38 66]]


##### Indexación y slicing: De la matriz obtenida, extrae la primera fila y la última columna. Imprime ambos resultados por separado.

In [6]:
# Extraer la primera fila
primera_fila = matriz[0]  # o también matriz[0, :]
print("\nPrimera fila:", primera_fila)
# Extraer la última columna
ultima_columna = matriz[:, -1]  # o también matriz[:, 4]
print("\nÚltima columna:", ultima_columna)


Primera fila: [71 21 24 32 93]

Última columna: [93 66]


##### Modificación: Cambia el valor de los elementos en la segunda fila a ceros.

In [7]:
# Cambiar segunda fila a ceros
matriz[1] = 0  # o también matriz[1, :] = 0
print("\nMatriz con segunda fila modificada:")
print(matriz)


Matriz con segunda fila modificada:
[[71 21 24 32 93]
 [ 0  0  0  0  0]]


#### Parte 2: Operaciones básicas con NumPy

##### Operaciones aritméticas

In [10]:
# Crear dos arrays de 5 elementos aleatorios entre 1 y 50
array1 = np.random.randint(1, 51, size=5)  # El límite superior es exclusivo
array2 = np.random.randint(1, 51, size=5)

print("Array 1:", array1)
print("Array 2:", array2)

Array 1: [11 36 47 42 35]
Array 2: [50 44 22 49 49]


In [11]:
# Suma de los arrays
suma = array1 + array2
print("\nSuma de los arrays:", suma)
# Multiplicación de los arrays (elemento por elemento)
multiplicacion = array1 * array2
print("Multiplicación de los arrays:", multiplicacion)


Suma de los arrays: [61 80 69 91 84]
Multiplicación de los arrays: [ 550 1584 1034 2058 1715]


In [12]:
# Calcular promedio (mean)
promedio_suma = np.mean(suma)
promedio_multiplicacion = np.mean(multiplicacion)

# Calcular desviación estándar (std)
desv_est_suma = np.std(suma)
desv_est_multiplicacion = np.std(multiplicacion)

print("\nEstadísticas de la suma:")
print(f"Promedio: {promedio_suma:.2f}")
print(f"Desviación estándar: {desv_est_suma:.2f}")

print("\nEstadísticas de la multiplicación:")
print(f"Promedio: {promedio_multiplicacion:.2f}")
print(f"Desviación estándar: {desv_est_multiplicacion:.2f}")


Estadísticas de la suma:
Promedio: 77.00
Desviación estándar: 10.71

Estadísticas de la multiplicación:
Promedio: 1388.20
Desviación estándar: 533.26


##### Condiciones lógicas

In [13]:
array = np.random.random(20)
print("Array original:", array)

Array original: [0.17182067 0.76129735 0.84569252 0.05324698 0.77551135 0.72067344
 0.62038757 0.29044914 0.91410241 0.87603093 0.8225049  0.28624608
 0.45700179 0.56102247 0.64432815 0.30011605 0.82756329 0.57191118
 0.21008023 0.18861037]


In [14]:
array[array < 0.5] = 0

print("\nArray después del reemplazo:")
print(array)


Array después del reemplazo:
[0.         0.76129735 0.84569252 0.         0.77551135 0.72067344
 0.62038757 0.         0.91410241 0.87603093 0.8225049  0.
 0.         0.56102247 0.64432815 0.         0.82756329 0.57191118
 0.         0.        ]


In [15]:
array[array > 0.5] = 1

print("\nArray después del reemplazo:")
print(array)


Array después del reemplazo:
[0. 1. 1. 0. 1. 1. 1. 0. 1. 1. 1. 0. 0. 1. 1. 0. 1. 1. 0. 0.]


##### Producto escalar

In [16]:
# Crear dos matrices 3x3 con números aleatorios enteros para mejor legibilidad
matriz1 = np.random.randint(1, 10, size=(3, 3))
matriz2 = np.random.randint(1, 10, size=(3, 3))

print("Matriz 1:")
print(matriz1)
print("\nMatriz 2:")
print(matriz2)

# Calcular el producto escalar usando np.dot
producto_escalar = np.dot(matriz1, matriz2)
# Alternativamente podríamos usar: matriz1 @ matriz2

print("\nProducto escalar:")
print(producto_escalar)

# Mostrar el proceso de cálculo para la primera posición [0,0]
print("\nDemostración del cálculo para la posición [0,0]:")
print(f"({matriz1[0,0]} × {matriz2[0,0]}) + ({matriz1[0,1]} × {matriz2[1,0]}) + ({matriz1[0,2]} × {matriz2[2,0]}) = {producto_escalar[0,0]}")

Matriz 1:
[[9 2 5]
 [9 1 4]
 [7 4 4]]

Matriz 2:
[[7 3 1]
 [6 9 1]
 [2 7 7]]

Producto escalar:
[[85 80 46]
 [77 64 38]
 [81 85 39]]

Demostración del cálculo para la posición [0,0]:
(9 × 7) + (2 × 6) + (5 × 2) = 85


#### Parte 3: Análisis de datos con NumPy

##### Matriz de datos

In [27]:
import pandas as pd

# Generar matriz de datos aleatorios
datos = np.random.randint(1, 21, size=(5, 4))

# Crear DataFrame con nombres descriptivos
df = pd.DataFrame(
    datos,
    columns=['Altura', 'Peso', 'Edad', 'Presión arterial'],
    index=['Persona 1', 'Persona 2', 'Persona 3', 'Persona 4', 'Persona 5']
)

print("Matriz de datos de personas:")
print(df)


Matriz de datos de personas:
           Altura  Peso  Edad  Presión arterial
Persona 1       3    12     8                 3
Persona 2       1     3     5                15
Persona 3      14     3     1                 5
Persona 4      14     7     9                15
Persona 5      15    10    13                19


##### Estadísticas

In [28]:
# Calcular la media de cada columna
media_columnas = df.mean()

print("Media de cada columna:")
print(media_columnas)


Media de cada columna:
Altura               9.4
Peso                 7.0
Edad                 7.2
Presión arterial    11.4
dtype: float64


In [29]:
# Encontrar el valor máximo de cada fila
max_filas = df.max(axis=1)

# Encontrar el valor mínimo de cada fila
min_filas = df.min(axis=1)

print("Valor máximo de cada fila:")
print(max_filas)

print("\nValor mínimo de cada fila:")
print(min_filas)


Valor máximo de cada fila:
Persona 1    12
Persona 2    15
Persona 3    14
Persona 4    15
Persona 5    19
dtype: int32

Valor mínimo de cada fila:
Persona 1     3
Persona 2     1
Persona 3     1
Persona 4     7
Persona 5    10
dtype: int32


In [30]:
# Ordenar las filas según los valores de la columna "Peso"
df_ordenado = df.sort_values(by='Peso')

print("DataFrame ordenado por 'Peso':")
print(df_ordenado)


DataFrame ordenado por 'Peso':
           Altura  Peso  Edad  Presión arterial
Persona 2       1     3     5                15
Persona 3      14     3     1                 5
Persona 4      14     7     9                15
Persona 5      15    10    13                19
Persona 1       3    12     8                 3
